### ISSUE TITLE
Are you guys in production with traject?

### ISSUE THREAD

**Issue by billdueber** [Brown-University-Library/bul-traject#1]
Traject 2.0 is going to come out Any Day Now and I'd like to update the readme with links to folks using it in a production or quasi-production capacity. Does that include Brown?

**Comment by lawlesst** [comment]
Our [search tool](https://search.library.brown.edu/) that uses the index built with Traject has recently entered a public "beta" phase.  So I would say, yes, we are using it in production. 

Thanks for checking. 
Ted
